#!/bin/bash

CLASSPATH=$CLASSPATH:($PWD/ultraLs)

chemin=""
pd=0
pf=0

for i in $*
do
	cd $1 2>/dev/null && chemin=$PWD
	echo $1 | grep "-" >/dev/null && echo $1 | grep d >/dev/null && pd=1
	echo $1 | grep "-" >/dev/null && echo $1 | grep f >/dev/null && pf=1
	echo $1 | grep "-" >/dev/null && echo $1 | grep c >/dev/null && pc="-c"
	echo $1 | grep "-" >/dev/null && echo $1 | grep n >/dev/null && nil="$nil $i"
	shift
done

! echo $pc | grep c >/dev/null && UDIR='\033[34m' && UFIL='\033[1;33m'

echo $pd | grep $pf >/dev/null && pd=1 && pf=1

# echo chemin:$chemin pd:$pd pf:$pf
# echo #:$#

bool=0

if echo $pd | grep 1 >/dev/null && echo $pf | grep 0 >/dev/null
then
	for i in $(ls $pa)
	do
		cd $i 2>/dev/null && echo -e ${UDIR}$PWD/${UDIR} && ./ultraLs -d $pc && cd ..
	done
fi

if echo $pd | grep 0 >/dev/null && echo $pf | grep 1 >/dev/null
then
	for i in $(ls $pa)
	do
		cd $i 2>/dev/null && ./ultraLs -f $pc && cd ..
		cd $i 2>/dev/null && cd .. || echo -e ${UFIL}$PWD/$i${UFIL}
	done
fi

if echo $pd | grep $pf >/dev/null
then
	for i in $(ls $pa)
	do
		cd $i 2>/dev/null && echo -e ${UDIR}$PWD/${UDIR} && ./ultraLs -df $pc && cd ..
		cd $i 2>/dev/null && cd .. || echo -e ${UFIL}$PWD/$i${UFIL}
	done
fi

#Made by MaitreKwin 
